server:
  port: 9090

# datasource and connection pool
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.77:3306/chart
    username: root
    password: talent123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
