server:
  port: 9090

# datasource and connection pool
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.7.212.241:17306/judgeAnalysis
    username: analysis
    password: analysis
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
